### ISSUE TITLE
您好，请指教一下

### ISSUE THREAD

**Issue by hostclsecho** [wangeasy6/RQ_HMS#2]
我跑您的程序，只用视频和温湿度模块（温湿度模块直接用杜邦线直接树莓派引脚），视频模块完全没问题，但是温湿度时好时坏，造成程序闪退，不知怎么回事？能说下您的硬件详细连接情况，或者发张硬件照片吗？谢谢

**Comment by wangeasy6** [comment]
在接DHT11的时候，Data引脚上接一个5K的上拉电阻可能解决“温湿度时好时坏”的问题
